/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void appInstantiates() {
        App classUnderTest = new App();
        assertNotNull("app should not be null", classUnderTest);
    }
}
